# Basic
title: Daniel Xie
subtitle: 生命在祂里头，这生命就是人的光
description: 

url: "http://danielxie.top"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Daniel Xie's Blog

# Navigation buttons in the front page.
nav:
    - {title: 作品, description: 个人作品, url: 'http://blog.danielxie.xyz/me/works'}
    # - {title: 关于, description: 自我介绍, url: 'http://me.danielxie.xyz'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 
    # duoshuo: 
    
# Social
social:
    weibo: xieshangxu
    github: xieshangxu
    mail: daniel.x1005@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
